### ISSUE TITLE
32bits issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by ThierryGoubier** [akgrant43/pharo-snap#3]
It seems a library is probably missing or is incorrect:

```
/snap/pharo/10/usr/bin/pharo : ligne 43 : 15057 Appel système erroné  $pharoexe $origargs
```
Version of the snap is: 6.1.0.0-2578-6a2c4f4

64bits works fine on the same system.

**Comment by akgrant43** [comment]
Hi Thierry,

I'm not at my computer at the moment but I think this will be an issue with
the core snap.

If you check the output of

sudo snap info core

The installed version will be 23xx (from memory).

You can:

sudo snap refresh core --beta

Which is what I've done.

Cheers,
Alistair

On 26 Jul. 2017 13:59, "Thierry Goubier" <notifications@github.com> wrote:

It seems a library is probably missing or is incorrect:

/snap/pharo/10/usr/bin/pharo : ligne 43 : 15057 Appel système erroné
$pharoexe $origargs

Version of the snap is: 6.1.0.0-2578-6a2c4f4

64bits works fine on the same system.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akgrant43/pharo-snap/issues/3>, or mute the thread

**Comment by ThierryGoubier** [comment]
Hi @akgrant43 ,

refreshing the snap core solved it.

Thanks!

Thierry

**Comment by akgrant43** [comment]
Hi Thierry,

It looks like core 2462 has been promoted to stable.  You can of course continue to use beta versions if you want to, but I've switched back to stable:

sudo snap refresh core --stable

Cheers,
Alistair

**Comment by ThierryGoubier** [comment]
Hi Alistair,

thanks. I've done the switch to stable for snap core.

Regards,

Thierry
